version: "3"
services:
  grp:
    container_name: grp
    image: frolvlad/alpine-python3:latest
    build: .
    environment:
      - FLASK_APP=web/app.py
      - FLASK_DEBUG=1
      - FLASK_ENV=development
      - GUNICORN_CMD_ARGS=--reload --log-level=debug
      - LOG_LEVEL=DEBUG
      - VIRTUAL_HOST=grp.docker
    ports:
      - 5000:5000
    volumes:
      - ${PWD}:/app

  # grp-test:
  #   container_name: grp-test
  #   extends: grp-base
  #   environment:
  #     - FLASK_DEBUG
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #     args:
  #       - EXTRA_REQUIREMENTS=requirements-dev.txt
  #       - GITHUB_TOKEN
  #   volumes:
  #     - ${PWD}:/app
  #   command:
  #     [
  #       "python",
  #       "-m",
  #       "pytest",
  #       "-s",
  #       "-vv",
  #       "--cov-report=term-missing",
  #       "--cov=grp",
  #       "--cov-config=setup.cfg",
  #       "--cov-fail-under=100",
  #       "grp/tests",
  #     ]
